Repository allinbits/cosmos-cash, pull requests merged in 2021-10, with the labels that each got.

#270 docs: publish docs website
  .github/workflows/docs.yaml
  .gitignore
  docs/Explanation/ADR/README.md
  docs/Explanation/ADR/adr-005-registration-credential.md
  docs/Explanation/ADR/adr-006-license-credential.md
  docs/Explanation/README.md
  docs/Explanation/articles/makefile
  docs/Explanation/articles/regulation-paper/rpts/CosmosCashRegs.md
  docs/README.md
  docs/Reference/MODULES.md
  docs/Reference/README.md
  mkdocs.yml
Labels: documentation

#260 docs: add security and privacy considerations
  docs/Explanation/ADR/adr-004-did.md
Labels: documentation, Design

#276 Enhance #275 message server test
  x/did/keeper/msg_server_test.go
Labels: enhancement

#294 fix: extract X25519ECDHKW pubkey from aries response
  x/did/client/cli/aries.go
Labels: bug
