Repository allinbits/cosmos-cash, pull requests merged in 2021-08, with the labels that each got.

#179 feat: add support for DID Metadata
  go.mod
  proto/did/did.proto
  proto/did/query.proto
  x/did/client/cli/cli_test.go
  x/did/client/cli/tx.go
  x/did/keeper/did.go
  x/did/keeper/grpc_query.go
  x/did/keeper/handler_test.go
  x/did/keeper/keeper_test.go
  x/did/keeper/msg_server.go
  x/did/types/did.go
  x/did/types/did.pb.go
  x/did/types/did_test.go
  x/did/types/keys.go
  x/did/types/query.pb.go
  x/issuer/ante/ante.go
Labels: feature

#176 docs: Add message formats to contributing.md
  .gitignore
  CONTRIBUTING.md
  Makefile
  TECHNICAL-SETUP.md
Labels: documentation

#184 feat: improve support for verification material
  go.mod
  go.sum
  proto/did/did.proto
  x/did/client/cli/tx.go
  x/did/docs/testing.md
  x/did/keeper/grpc_query.go
  x/did/keeper/grpc_query_test.go
  x/did/keeper/handler_test.go
  x/did/keeper/msg_server.go
  x/did/module.go
  x/did/resolver/doc.go
  x/did/resolver/resolution.go
  x/did/resolver/resolver.go
  x/did/types/did.go
  x/did/types/did.pb.go
  x/did/types/did_test.go
  x/did/types/errors.go
  x/did/types/keys.go
  x/did/types/msg.go
  x/did/types/msg_test.go
  x/issuer/ante/ante.go
  x/issuer/types/tx.pb.go
Labels: enhancement, Security

#168 feat(docs): READMEs for docs, Explanation and Reference Documentation (#148)
  docs/Explanation/README.md
  docs/Explanation/articles/README.md
  docs/Explanation/presentations.md
  docs/README.md
  docs/Reference/README.md
Labels: documentation

#203 docs: improve main readme
  README.md
  docs/Reference/MODULES.md
Labels: documentation, enhancement

#220 feat: support cosmos-sdk-v0.43 key format
  x/did/client/cli/tx.go
  x/did/keeper/handler_test.go
  x/did/resolver/resolver.go
  x/did/types/did.go
  x/did/types/did_test.go
  x/did/types/errors.go
  x/did/types/msg_test.go
  x/issuer/ante/ante.go
Labels: feature, BREAKING
